named_arrays Documentation
Kankelborg-Group/named_arrays pull request #2
Opened 2023-01-05 15:16 UTC by jacobdparker

Initial pull request to incoorperate documentation for scalars/core.py .  Documentation may be a little colloquial, and in some cases illustrate possibly unintended use cases (see ScalarArrayRange).

2023-01-05 21:11 UTC, byrdie requested changes

2023-01-05 21:11 UTC, byrdie commented on named_arrays/scalars/core.py
> +    Scalar array range can be used to create a ScalarArray of integers.
I think you can link to `ScalarArray` using `` :class:`ScalarArray` ``

2023-01-05 21:11 UTC, byrdie commented on named_arrays/scalars/core.py
> +    Note above that x does not include stop, and won't in almost all cases.  ScalarArrayRange can be used to create
Link to `ScalarArrayRange` using `` :class:`ScalarArrayRange` ``

2023-01-05 21:11 UTC, byrdie commented on named_arrays/scalars/core.py
> +    For the above, and more complicated uses, it is recommended to use ScalarLinearSpace instead.  See numpy documentation
Link to `ScalarLinearSpace` using `` :class:`ScalarLinearSpace` ``

2023-01-05 21:11 UTC, byrdie commented on named_arrays/scalars/core.py
> +    An evenly spaced ScalarArray ranging from start to stop with num elements.
Link to `ScalarArray` using `` :class:`ScalarArray` ``

2023-01-05 21:11 UTC, byrdie commented on named_arrays/scalars/core.py
> +    Most often ScalarArrays won't be formed directly from a np.array, but through more useful routines like ScalarLinearSpace,
Add links to `ScalarArray`, `numpy.ndarray`, and `ScalarLinearSpace`.

2023-01-05 21:11 UTC, byrdie commented on named_arrays/scalars/core.py
> +    a named_arrays equivalent to np.linspace.  For example, one can quickly create an evenly spaced coordinate (or axis) array with units.
Add link to `numpy.linspace`.

2023-01-05 21:11 UTC, byrdie commented on named_arrays/scalars/core.py
> +        Photon_Energy = na.ScalarLinearSpace(1, 25, axis="Energy", num = 25) * u.keV
Use PEP8 naming conventions by changing `Photon_Energy` to `photon_energy`.

2023-01-05 21:11 UTC, byrdie commented on named_arrays/scalars/core.py
> +        Wavelength = 1240 * u.eV * u.nm / Photon_Energy
`Wavelength` variable should be lowercase per PEP8.

2023-01-07 00:33 UTC, byrdie commented on named_arrays/scalars/array_functions.py
> +    if where is not None and not np._NoValue:
Looks like we made a naive error here.

```suggestion
    if where is not None and where is not np._NoValue:
```

2023-01-07 03:48 UTC, byrdie commented on named_arrays/scalars/array_functions.py
> +    if where is not None and not np._NoValue:
I just fixed this in `main` since I needed it to work for other tests. Delete this change and merge in from main.

2023-01-09 21:21 UTC, jacobdparker commented
All comments should be resolved.  When you do the suggested change, I can implement them locally in a single click.

2023-01-09 22:52 UTC, byrdie requested changes
Added a few more updates

2023-01-09 22:52 UTC, byrdie commented on named_arrays/scalars/core.py
> +    A ScalarArray is defined by a :class:`numpy.ndarray` and an axis.
```suggestion
    A :class:`ScalarArray` is defined by a :class:`numpy.ndarray` and an axis.
```

2023-01-09 22:52 UTC, byrdie commented on named_arrays/scalars/core.py
> +    What happens when we do math with ScalarArrays?
```suggestion
    What happens when we do math with :class:`ScalarArray`s?
```

2023-01-09 22:52 UTC, byrdie commented on named_arrays/scalars/core.py
> +    Note how when performing mathematical operations on two ScalarArrays with different axes, the arrays are
```suggestion
    Note how when performing mathematical operations on two :class:`ScalarArray`s with different axes, the arrays are
```

2023-01-09 22:52 UTC, byrdie commented on named_arrays/scalars/core.py
> +    We can also use reduction operators (mean, sum, etc) on ScalarArrays, and if desired specify the axis by name without
```suggestion
    We can also use reduction operators (mean, sum, etc) on :class:`ScalarArray`s, and if desired specify the axis by name without
```

2023-01-09 22:52 UTC, byrdie commented on named_arrays/scalars/core.py
> +    A :class:`ScalarArray` over the range [start, stop) in incremented by step. An analog to :class:`numpy.arange`.
```suggestion
    A :class:`ScalarArray` over the range [:attr:`start`, :attr:`stop`) incremented by :attr:`step`. An analog to :class:`numpy.arange`.
```

2023-01-09 22:52 UTC, byrdie commented on named_arrays/scalars/core.py
> +    ScalarArrayRange can be used to create a :class:`ScalarArray` of integers.
```suggestion
    :class:`ScalarArrayRange` can be used to create a :class:`ScalarArray` of integers.
```

2023-01-09 22:52 UTC, byrdie commented on named_arrays/scalars/core.py
> +    Note above that x does not include stop, and won't in almost all cases.  :class:`ScalarArrayRange` can be used to
```suggestion
    Note above that ``x`` does not include :attr:`stop`, and won't in almost all cases.  :class:`ScalarArrayRange` can be used to
```

2023-01-09 22:52 UTC, byrdie commented on named_arrays/scalars/core.py
> +    create an increasing ScalarArray of floats, even with non integer steps.
```suggestion
    create an increasing :class:`ScalarArray` of :class:`float`s, even with non integer steps.
```

2023-01-09 22:52 UTC, byrdie commented on named_arrays/scalars/core.py
> +    Most often ScalarArrays won't be formed directly from a :class:`numpy.ndarray`, but through more useful routines
```suggestion
    Most often :class:`ScalarArray`s won't be formed directly from a :class:`numpy.ndarray`, but through more useful routines
```

2023-01-09 22:52 UTC, byrdie commented on named_arrays/scalars/core.py
> +    knowledge of the corresponding index axes of the original array.
```suggestion
    knowledge of the axis index in the original array.
```

2023-01-10 14:14 UTC, jacobdparker commented
Applied all changes locally.  Will keep better track of labeling functions/variables correctly in future documentation.

2023-01-10 17:56 UTC, merged